/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applicationfinale;

import applicationfinale.Affine.JFrameAffine;
import applicationfinale.Cesar.JFrameCesar;

import applicationfinale.Hill.FrameHill;
import applicationfinale.Multiplication.JFrameMultiplication;
import applicationfinale.RSA.RSAFrame;

import applicationfinale.Vigenere.JFrameVigenere;

import javax.swing.ButtonGroup;

/**
 *
 * @author ayoub
 */
public class Cryptographies extends javax.swing.JFrame {

    /**
     * Creates new form Acceuil
     */
    public Cryptographies() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        SUIVANT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CESARC = new javax.swing.JRadioButton();
        MULTIPLICATIONC = new javax.swing.JRadioButton();
        AFFINEC = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        HILLC = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        VIGENEREC = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        VIGENEREC1 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();

        jButton2.setBackground(new java.awt.Color(255, 255, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("EXIT ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 2, 5, 2, new java.awt.Color(255, 255, 51)));

        SUIVANT.setBackground(new java.awt.Color(255, 255, 102));
        SUIVANT.setFont(new java.awt.Font("Kalinga", 1, 14)); // NOI18N
        SUIVANT.setText("SUIVANT  -->");
        SUIVANT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUIVANTActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("  Techniques de chiffrement par substitution");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 4, true));

        jLabel4.setBackground(new java.awt.Color(255, 255, 204));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 0));
        jLabel4.setText("Méthodes de substitution mono-grammiques:");

        group.add(CESARC);
        CESARC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CESARC.setText("CESAR");
        CESARC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CESARCActionPerformed(evt);
            }
        });

        group.add(MULTIPLICATIONC);
        MULTIPLICATIONC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MULTIPLICATIONC.setText("MULTIPLICATION");
        MULTIPLICATIONC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MULTIPLICATIONCActionPerformed(evt);
            }
        });

        group.add(AFFINEC);
        AFFINEC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AFFINEC.setText("AFFINE ");
        AFFINEC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFFINECActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Méthodes de substitution mono-alphabétiques :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 153, 0));
        jLabel5.setText(" Méthodes de substitution poly grammiques   :");

        group.add(HILLC);
        HILLC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        HILLC.setText("HILL");
        HILLC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HILLCActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("Méthode de substitution poly-alphabétique :");

        group.add(VIGENEREC);
        VIGENEREC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        VIGENEREC.setText("VIGENERE");
        VIGENEREC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VIGENERECActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 0));

        jButton1.setBackground(new java.awt.Color(255, 255, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("<-- PRECEDENT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        group.add(VIGENEREC1);
        VIGENEREC1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        VIGENEREC1.setText("RSA");
        VIGENEREC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VIGENEREC1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("Méthodede chiffrement RSA :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CESARC)
                                        .addGap(18, 18, 18)
                                        .addComponent(MULTIPLICATIONC)
                                        .addGap(18, 18, 18)
                                        .addComponent(AFFINEC))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel3))
                        .addContainerGap(68, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(VIGENEREC1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                        .addComponent(SUIVANT, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(HILLC))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(VIGENEREC, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CESARC)
                    .addComponent(MULTIPLICATIONC)
                    .addComponent(AFFINEC))
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(HILLC)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addComponent(VIGENEREC)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(VIGENEREC1)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SUIVANT, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VIGENERECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VIGENERECActionPerformed

        testVigenereC=true;
        testMultiplicationC=false;
        testCesarC=false;
        testCesarC=false;
        testAffineC =false;
        testHillC=false;
        RSAc=false;
       
    }//GEN-LAST:event_VIGENERECActionPerformed

    private void HILLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HILLCActionPerformed
        // TODO add your handling code here:
        testHillC=true;
        testMultiplicationC=false;
        testCesarC=false;
        RSAc=false;
        testAffineC =false;

        testVigenereC=false;
        
    }//GEN-LAST:event_HILLCActionPerformed

    private void AFFINECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFFINECActionPerformed
        // TODO add your handling code here:
         RSAc=false;
        testAffineC =true;
        testMultiplicationC=false;
        testCesarC=false;
        testCesarC=false;
        testHillC=false;
        testVigenereC=false;
       
    }//GEN-LAST:event_AFFINECActionPerformed

    private void MULTIPLICATIONCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MULTIPLICATIONCActionPerformed
        // TODO add your handling code here:
        testMultiplicationC= true;
        testCesarC=false;
        RSAc=false;
        testAffineC =false;
        testHillC=false;
        testVigenereC=false;
        
    }//GEN-LAST:event_MULTIPLICATIONCActionPerformed

    private void CESARCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CESARCActionPerformed
        testCesarC=true;
        testAffineC =false;
        testMultiplicationC=false;
        testHillC=false;
        testVigenereC=false;
        RSAc=false;
        
    }//GEN-LAST:event_CESARCActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void SUIVANTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUIVANTActionPerformed
        // applicationfinale.Hill.Affichage ex1 = new  applicationfinale.Hill.Affichage();
        // ex1.setVisible(true);
        // cryptographie
        JFrameCesar c = new JFrameCesar();
        JFrameMultiplication m = new  JFrameMultiplication();
        JFrameAffine  a = new  JFrameAffine();
        FrameHill h  = new  FrameHill();
        JFrameVigenere v = new JFrameVigenere();
        
       
        
        
        if(RSAc==true){
            RSAFrame rsa=new RSAFrame(); 
            rsa.setVisible(true);

        }

        if(testCesarC==true){
            c.setVisible(true);

        }

        if(testMultiplicationC==true){
            m.setVisible(true);

        }

        if(testAffineC==true){
            a.setVisible(true);
        }

        if(testHillC==true){
            h.setVisible(true);
        }

        if (testVigenereC==true){
            v.setVisible(true);
        }
       
    }//GEN-LAST:event_SUIVANTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void VIGENEREC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VIGENEREC1ActionPerformed
        // TODO add your handling code here:
        RSAc=true;
        testCesarC=false;
        testAffineC =false;
        testMultiplicationC=false;
        testHillC=false;
        testVigenereC=false;
        testCesarS=false;
        testAffineS =false;
        testMultiplicationS=false;
        testHillS=false;
        testVigenereS=false;
    }//GEN-LAST:event_VIGENEREC1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cryptographies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cryptographies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cryptographies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cryptographies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cryptographies().setVisible(true);
            }
        });
    }
    ButtonGroup group = new ButtonGroup();
    boolean RSAc=false;
    boolean testCesarC=false;
    boolean  testAffineC =false;
    boolean testMultiplicationC=false;
    boolean  testHillC=false;
    boolean testVigenereC=false;
    
     boolean testCesarS=false;
    boolean  testAffineS =false;
    boolean testMultiplicationS=false;
    boolean  testHillS=false;
    boolean testVigenereS=false;
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AFFINEC;
    private javax.swing.JRadioButton CESARC;
    private javax.swing.JRadioButton HILLC;
    private javax.swing.JRadioButton MULTIPLICATIONC;
    private javax.swing.JButton SUIVANT;
    private javax.swing.JRadioButton VIGENEREC;
    private javax.swing.JRadioButton VIGENEREC1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
