/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applicationfinale.Affine;

import javax.swing.ButtonGroup;

/**
 *
 * @author ayoub
 */
public class JFrameAffine extends javax.swing.JFrame {

    /**
     * Creates new form JFrameAffine
     */
    public JFrameAffine() {
            	setTitle("\t\t\t\t\tLA METHODE AFFINE "); 

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TEXTE = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        cleaA = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        clebA = new javax.swing.JTextField();
        CRYPTERA = new javax.swing.JRadioButton();
        DECRYPTERA = new javax.swing.JRadioButton();
        VALIDER = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        AFFICHAGE = new javax.swing.JTextPane();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("MESSAGE :");

        TEXTE.setColumns(20);
        TEXTE.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        TEXTE.setRows(5);
        jScrollPane1.setViewportView(TEXTE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("a =");

        cleaA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cleaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleaAActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("b  =");

        clebA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        clebA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clebAActionPerformed(evt);
            }
        });

        group.add(CRYPTERA);
        CRYPTERA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CRYPTERA.setText("CRYPTER");
        CRYPTERA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CRYPTERAActionPerformed(evt);
            }
        });

        group.add(DECRYPTERA);
        DECRYPTERA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DECRYPTERA.setText("DECRYPTER");
        DECRYPTERA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DECRYPTERAActionPerformed(evt);
            }
        });

        VALIDER.setBackground(new java.awt.Color(255, 255, 51));
        VALIDER.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        VALIDER.setText("VALIDER");
        VALIDER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VALIDERActionPerformed(evt);
            }
        });

        AFFICHAGE.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jScrollPane2.setViewportView(AFFICHAGE);

        jButton2.setBackground(new java.awt.Color(255, 255, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("<-- PRECEDENT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cleaA, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clebA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(DECRYPTERA)
                        .addGap(48, 48, 48)
                        .addComponent(CRYPTERA))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(VALIDER, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 16, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cleaA, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clebA, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DECRYPTERA)
                        .addComponent(CRYPTERA)))
                .addGap(39, 39, 39)
                .addComponent(VALIDER, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cleaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cleaAActionPerformed

    private void clebAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clebAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clebAActionPerformed

    private void CRYPTERAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CRYPTERAActionPerformed
        String c ="\t\t      METHODE D' AFFINE (CRYPTER) \n\n\n";
    	String[] bString = new String[TEXTE.getText().length()];
		String etape1="";String etape1F ="";
		String etape2="";String etape2F ="";
		String etape3="";String etape3F ="";
		String etape4="";String etape4F ="";
		
		
		for (int i = 0; i <= 11; i++) {
 			if (Integer.parseInt(cleaA.getText()) == tabcle[i]) {
					test++;
				}
			}
    	
    	if(test==0){
    		clickcrypter="erreurCA";
                clickdecrypter="";
    		
    	}
		
    	else{
		
		
		for (int i = 0; i <TEXTE.getText().replaceAll("\\s","").length(); i++) {
			bString[i] = s.codageNum(TEXTE.getText().replaceAll("\\s","").charAt(i));
		}
		for(int i=0;i<TEXTE.getText().replaceAll("\\s","").length();i++){
		etape1=etape1.concat("  Cn("+TEXTE.getText().replaceAll("\\s","").charAt(i)+")="+bString[i]+"    "); }
    	etape1F="    eatpe 1  : codage numerique\t : "+etape1;
    	
    	
    	
    	
    	// on va convertir les elements de tableau bString " String "
		// dans un taableau bEntier en  "entier"

		int[] bEntier = new int[TEXTE.getText().replaceAll("\\s","").length()];
		for (int i = 0; i < TEXTE.getText().replaceAll("\\s","").length(); i++) {
			bEntier[i] = Integer.parseInt(bString[i]);
		}
    	
		// etape 2 : on va stocker toute les chiffrement 
		// dans un tableau de type entier qui s'appele bChiffre

		int[] bChiffre = new int[TEXTE.getText().replaceAll("\\s","").length()];
		for (int i = 0; i < TEXTE.getText().replaceAll("\\s","").length(); i++) {
				bChiffre[i]=s.chiffrementA(bEntier[i],Integer.parseInt(cleaA.getText()),Integer.parseInt(clebA.getText()));
		}
		
		for (int i = 0; i < TEXTE.getText().replaceAll("\\s","").length(); i++) {
			etape2 =etape2.concat("C("+bString[i]+")="+bChiffre[i]+"    ") ;
	       }
		etape2F=etape1F+"\n\n    eatpe 2  : chiffrement\t\t :" +etape2;
		
		
		
		
		// traitement de  etat3 : decodage numerique P(i)
		char [] btextchiffre = new char[TEXTE.getText().replaceAll("\\s","").length()];
		for(int i=0;i<TEXTE.getText().replaceAll("\\s","").length();i++){
			if(Character.isUpperCase(TEXTE.getText().replaceAll("\\s","").charAt(i))){
			btextchiffre[i]=s.decodeNummajuscule(bChiffre[i]);}
			else{btextchiffre[i]=s.decodeNumminiscule(bChiffre[i]);}
		}
    	
		
		// affichage finale du text crypté 
		
		for(int i=0;i<TEXTE.getText().replaceAll("\\s","").length();i++){
			etape3=etape3.concat("Cn^-1("+bChiffre[i]+")="+btextchiffre[i] +"   ");
		}
		etape3F=etape2F+"\n\n    etape 3: decodage numerique\t :"+etape3;
		
		
		for(int i=0;i<TEXTE.getText().replaceAll("\\s","").length();i++){
			etape4=etape4.concat(btextchiffre[i]+"");
		}
    	
    	etape4F=c+etape3F+"\n\n\n"+"#################################   AFFICHAGE FINAL   ##################################"+"\n\n"+" \t\t\t\t*********    "+etape4+"  ********";
    	for (int i = 0; i <= 11; i++) {
 			if (Integer.parseInt(cleaA.getText()) == tabcle[i]) {
					test++;
				}
			}
    	
    	if(test==0){
    		CRYPTERA.setActionCommand("entrer une valeur parmis {3,5,7,11,15,17,19,23,25}");
    	}
    	else{
    	CRYPTERA.setActionCommand(etape4F);}
    	
    //	CRYPTER.setActionCommand(etape3F);
    	
    
		clickcrypter="CA";
                clickdecrypter="";
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_CRYPTERAActionPerformed

    private void DECRYPTERAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DECRYPTERAActionPerformed
        String c ="\t\t\t      METHODE D' AFFINE (DECRYPTER) \n\n\n";
    	String[] bString = new String[TEXTE.getText().length()];
		String etape1="";String etape1F ="";
		String etape2="";String etape2F ="";
		String etape3="";String etape3F ="";
		String etape4="";String etape4F ="";
		
		for (int i = 0; i <= 11; i++) {
 			if (Integer.parseInt(cleaA.getText()) == tabcle[i]) {
					test++;
				}
			}
    	
    	if(test==0){
    		clickdecrypter="erreurDA";
                clickcrypter="";
    		
    	}
		
    	else{
		
		
		for (int i = 0; i <TEXTE.getText().replaceAll("\\s","").length(); i++) {
			bString[i] = s.codageNum(TEXTE.getText().replaceAll("\\s","").charAt(i));
		}
		for(int i=0;i<TEXTE.getText().replaceAll("\\s","").length();i++){
		etape1=etape1.concat("  Cn("+TEXTE.getText().replaceAll("\\s","").charAt(i)+")="+bString[i]+"    "); }
    	etape1F="    eatpe 1  : codage numerique \t: "+etape1;
    	
    	
    	
    	
    	// on va convertir les elements de tableau bString " String "
		// dans un taableau bEntier en  "entier"

		int[] bEntier = new int[TEXTE.getText().replaceAll("\\s","").length()];
		for (int i = 0; i < TEXTE.getText().replaceAll("\\s","").length(); i++) {
			bEntier[i] = Integer.parseInt(bString[i]);
		}
    	
		// etape 2 : on va stocker toute les chiffrement 
		// dans un tableau de type entier qui s'appele bChiffre

		int[] bChiffre = new int[TEXTE.getText().replaceAll("\\s","").length()];

		
    	
		for (int i = 0; i < TEXTE.getText().replaceAll("\\s","").length(); i++) {
				bChiffre[i]=s.dechiffrementA(bEntier[i],Integer.parseInt(cleaA.getText()),Integer.parseInt(clebA.getText()));
		}
		
		for (int i = 0; i < TEXTE.getText().replaceAll("\\s","").length(); i++) {
			etape2 =etape2.concat("C("+bString[i]+")="+bChiffre[i]+"    ") ;
	       }
		etape2F=etape1F+"\n\n    eatpe 2  : dechiffrement \t  : " +etape2;
		
		
		
		
		// traitement de  etat3 : decodage numerique P(i)
		char [] btextchiffre = new char[TEXTE.getText().replaceAll("\\s","").length()];
		for(int i=0;i<TEXTE.getText().replaceAll("\\s","").length();i++){
			if(Character.isUpperCase(TEXTE.getText().replaceAll("\\s","").charAt(i))){
			btextchiffre[i]=s.decodeNummajuscule(bChiffre[i]);}
			else{btextchiffre[i]=s.decodeNumminiscule(bChiffre[i]);}
		}
    	
		
		// affichage finale du text crypté 
		
		for(int i=0;i<TEXTE.getText().replaceAll("\\s","").length();i++){
			etape3=etape3.concat("Cn^-1("+bChiffre[i]+")="+btextchiffre[i] +"   ");
		}
		etape3F=etape2F+"\n\n    etape 3: decodage numerique\t :"+etape3;
		
		
		for(int i=0;i<TEXTE.getText().replaceAll("\\s","").length();i++){
			etape4=etape4.concat(btextchiffre[i]+"");
		}
    	
    	etape4F=c+etape3F+"\n\n\n"+"#################################   AFFICHAGE FINAL   ##################################"+"\n\n"+" \t\t\t\t*********    "+etape4+"  ********";
    	DECRYPTERA.setActionCommand(etape4F);
    	
    //	CRYPTER.setActionCommand(etape3F);
    	
    
		clickdecrypter="DA";
                clickcrypter="";
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_DECRYPTERAActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void VALIDERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VALIDERActionPerformed
        // TODO add your handling code here:
        if(clickcrypter.equals("CA")){
 	 	 	   AFFICHAGE.setText(CRYPTERA.getActionCommand());
 	 	 	  
 	 	 	   }else if(clickdecrypter.equals("DA")){
 	 	     	   AFFICHAGE.setText(DECRYPTERA.getActionCommand());
 	 	     	  	   }
 	 	 	else if(clickdecrypter.equals("erreurDA")||clickcrypter.equals("erreurCA")){
	 	     	   AFFICHAGE.setText("\n\n\n\n\n\t\t          /!\\vous avez pas entrer un nombre premier avec 26/!\\");
	 	     	  	   }
    }//GEN-LAST:event_VALIDERActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAffine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAffine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAffine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAffine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAffine().setVisible(true);
            }
        });
    }
    int  test = 0;
    Affine  s = new Affine();
    String  clickcrypter="";
    String  clickdecrypter="";
    ButtonGroup group = new  ButtonGroup();
        int tabcle[] = { 1, 3, 5, 7, 9, 11, 15, 17, 19, 21, 23, 25 };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane AFFICHAGE;
    private javax.swing.JRadioButton CRYPTERA;
    private javax.swing.JRadioButton DECRYPTERA;
    private javax.swing.JTextArea TEXTE;
    private javax.swing.JButton VALIDER;
    private javax.swing.JTextField cleaA;
    private javax.swing.JTextField clebA;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
