/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applicationfinale.CrypranalyseMultiplication;

import javax.swing.Action;
import javax.swing.ButtonGroup;

/**
 *
 * @author yahya
 */
public class MultiplicationAnalyse extends javax.swing.JFrame {

    /**
     * Creates new form MultiplicationAnalyse
     */
    public MultiplicationAnalyse() {
        setTitle("\t\t\t\t\tCRYPTANAYSE DE MULTIPLICATION "); 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TEXTE = new javax.swing.JTextArea();
        BRUTE = new javax.swing.JRadioButton();
        FREQUENCE = new javax.swing.JRadioButton();
        VALIDER = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        AFFICHER = new javax.swing.JTextPane();
        PRECEDENT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 0)));

        TEXTE.setColumns(20);
        TEXTE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TEXTE.setRows(5);
        jScrollPane1.setViewportView(TEXTE);

        group.add(BRUTE);
        BRUTE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BRUTE.setText("ATTAQUE PAR BRUTE");
        BRUTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRUTEActionPerformed(evt);
            }
        });

        group.add(FREQUENCE);
        FREQUENCE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FREQUENCE.setText("ATTAQUE PAR FREQUENCE");
        FREQUENCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FREQUENCEActionPerformed(evt);
            }
        });

        VALIDER.setBackground(new java.awt.Color(255, 255, 0));
        VALIDER.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        VALIDER.setText("VALIDER");
        VALIDER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VALIDERActionPerformed(evt);
            }
        });

        AFFICHER.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jScrollPane2.setViewportView(AFFICHER);

        PRECEDENT.setBackground(new java.awt.Color(255, 255, 0));
        PRECEDENT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PRECEDENT.setText("<-- PRECEDENT");
        PRECEDENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRECEDENTActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Message :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(BRUTE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FREQUENCE)
                .addGap(141, 141, 141))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(VALIDER, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(346, 346, 346))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(PRECEDENT, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(337, 337, 337))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addComponent(VALIDER, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BRUTE)
                                    .addComponent(FREQUENCE))
                                .addGap(64, 64, 64))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1)
                        .addGap(206, 206, 206)))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PRECEDENT, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FREQUENCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FREQUENCEActionPerformed
        // TODO add your handling code here:tr
        clickBrute=false;
        clickFrequence=true;
        String texte,solution="";
        texte=TEXTE.getText();
          char[] alp=new char[26];

        for(int i=0;i<26;i++){
            alp[i]=(char)('A'+i);
        }

        int[] tab=new int[26];
        for(int j=0;j<26;j++){
            int a=0;
            for(int i=0;i<texte.length();i++){
                if(texte.charAt(i)==alp[j]){

                    a=a+1;
                }
                tab[j]=a;
            }
        }
        for(int i=0;i<26;i++){
            if(tab[i]>=max){
                max=tab[i];
                indic=i+1;}
        }

        for (int i = 0; i < tab.length; i++) {
            if(tab[i]<max&&tab[i]>max1){
                max1=tab[i];
                indic1=i+1;
            }
        }
                String cl="";
            	int cle =1;
		for(int i=0;i<q.length;i++){
			if((q[i]*5)%26==indic){
				cle=q[i];
				cl="la cle utiliser "+cle;
			}
		}
                //solution="la cle utiliser "+cle+"\n\nle message est: \n";
                 solution=solution+"##########################################################################################\n#\n#\t\t\t\tJE SUIS  ATTACKER LA CLE :  "+cle+"\n# \n"
                + "# \n##########################################################################################\n#\n#\t\t\t\tLE TEXTE CLAIR EST  : ";
			int inv=clas.inverse(cle);
			//System.out.println("linve"+inv);
			for(int i=0;i<texte.length();i++){
				int codNum=clas.codageNum(texte.charAt(i));
				int chif=clas.dechiffrementM(codNum,inv);
				
				solution=solution+clas.decodeNummajuscule(chif);
				
				
			}
        
        solution=solution+"\n#\n#\n##########################################################################################";
        
        FREQUENCE.setActionCommand(solution);
        
    }//GEN-LAST:event_FREQUENCEActionPerformed

    private void BRUTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRUTEActionPerformed
        // TODO add your handling code here:
        clickBrute=true;
        clickFrequence=false;
        String texte,solution="";
        texte=TEXTE.getText();
        for (int i = 0; i < q.length; i++) {
					solution=solution+"\n#################################\t      pour k= "+q[i]+"          ###########################\n\n\t\t\t\t\t";
                                        
                                       
                                        
					for (int k = 0; k < texte.length(); k++) {
						
						int inv=clas.inverse(q[i]);
					int codNum=clas.codageNum(texte.charAt(k));
					int chif=clas.dechiffrementM(codNum,inv);
					
					solution=solution+clas.decodeNummajuscule(chif);
        
                                        }
                                        solution=solution+"\n\n";
        }
        BRUTE.setActionCommand(solution);
    }//GEN-LAST:event_BRUTEActionPerformed

    private void VALIDERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VALIDERActionPerformed
        // TODO add your handling code here:
        
        
        
        
        if(clickBrute==true){
            AFFICHER.setText(BRUTE.getActionCommand());
        }else if(clickFrequence==true){          
            AFFICHER.setText(FREQUENCE.getActionCommand());
           
        }
    }//GEN-LAST:event_VALIDERActionPerformed

    private void PRECEDENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRECEDENTActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_PRECEDENTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultiplicationAnalyse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultiplicationAnalyse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultiplicationAnalyse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultiplicationAnalyse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultiplicationAnalyse().setVisible(true);
            }
        });
    }
    int max=0;
		int max1=0;
		int indic=0;
		int indic1=0;
		int mx=0;
		int q[]={1,3,5,7,9,11,15,17,19,21,23,25};
     SubMonoAlph clas=new SubMonoAlph();
    ButtonGroup group = new ButtonGroup();
 boolean clickBrute,clickFrequence;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane AFFICHER;
    private javax.swing.JRadioButton BRUTE;
    private javax.swing.JRadioButton FREQUENCE;
    private javax.swing.JButton PRECEDENT;
    private javax.swing.JTextArea TEXTE;
    private javax.swing.JButton VALIDER;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
