/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applicationfinale.CryptanaliseCesar;


import javax.swing.ButtonGroup;

/**
 *
 * @author yahya
 */
public class CesarCryptanalyse extends javax.swing.JFrame {

    /**
     * Creates new form CesarCryptanalyse
     */
    public CesarCryptanalyse() {
        setTitle("\t\t\t\t\tCRYPTANALYSE DE CESAR  "); 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TEXTE = new javax.swing.JTextArea();
        BRUTE = new javax.swing.JRadioButton();
        Frequence = new javax.swing.JRadioButton();
        Precedent = new javax.swing.JToggleButton();
        VALIDER = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        AFFICHER = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 0)));
        jPanel1.setForeground(new java.awt.Color(102, 102, 255));

        TEXTE.setColumns(20);
        TEXTE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TEXTE.setRows(5);
        jScrollPane1.setViewportView(TEXTE);

        group.add(BRUTE);
        BRUTE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BRUTE.setText("ATTAQUE PAR BRUTE");
        BRUTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRUTEActionPerformed(evt);
            }
        });

        group.add(Frequence);
        Frequence.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Frequence.setText("ATTAQUE PAR FREQUENCE");
        Frequence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrequenceActionPerformed(evt);
            }
        });

        Precedent.setBackground(new java.awt.Color(255, 255, 51));
        Precedent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Precedent.setText("<-- PRECEDENT");
        Precedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecedentActionPerformed(evt);
            }
        });

        VALIDER.setBackground(new java.awt.Color(255, 255, 0));
        VALIDER.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        VALIDER.setText("VALIDER");
        VALIDER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VALIDERActionPerformed(evt);
            }
        });

        AFFICHER.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jScrollPane2.setViewportView(AFFICHER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Message :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(123, 123, 123)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(397, 397, 397)
                            .addComponent(VALIDER, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(399, 399, 399)
                            .addComponent(Precedent, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(BRUTE)
                        .addGap(97, 97, 97)
                        .addComponent(Frequence, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BRUTE)
                            .addComponent(Frequence))
                        .addGap(26, 26, 26)))
                .addComponent(VALIDER, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Precedent, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VALIDERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VALIDERActionPerformed
        // TODO add your handling code here:

        if(clickBrute==true ){

            AFFICHER.setText(BRUTE.getActionCommand());

        }else if(clickFrequence==true){
            AFFICHER.setText(Frequence.getActionCommand());
        }else{
            AFFICHER.setText("veillez cochez une case");
        }

    }//GEN-LAST:event_VALIDERActionPerformed

    private void FrequenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrequenceActionPerformed
        // TODO add your handling code here:
        clickBrute=false;
        clickFrequence=true;
        String texte,solu="";
        texte=TEXTE.getText().replaceAll("\\s","");
        //#########cherchre a eliminer les retoures a la ligne

        char[] alp=new char[26];

        for(int i=0;i<26;i++){
            alp[i]=(char)('A'+i);
        }

        int[] tab=new int[26];
        for(int j=0;j<26;j++){
            int a=0;
            for(int i=0;i<texte.length();i++){
                if(texte.charAt(i)==alp[j]){

                    a=a+1;
                }
                tab[j]=a;
            }
        }
        for(int i=0;i<26;i++){
            if(tab[i]>=max){
                max=tab[i];
                indic=i+1;}
        }

        for (int i = 0; i < tab.length; i++) {
            if(tab[i]<max&&tab[i]>max1){
                max1=tab[i];
                indic1=i+1;
            }
        }
        int ke=indic-5;
        int cle=26-ke;
        solu=solu+"##########################################################################################\n#\n#\t\t\t\tJE SUIS  ATTACKER LA CLE :  "+cle+"\n# \n"
                + "# \n##########################################################################################\n#\n#\t\t\t\tLE TEXTE CLAIR EST  : ";
        System.out.println("");

        for (int i = 0; i < texte.length(); i++) {
            int codNum=clas.codageNum(texte.charAt(i));
            int chif=clas.dechiffrementC(codNum,ke);
            solu=solu+clas.decodeNummajuscule(chif)+"";
        }
        solu=solu+"\n#\n#\n##########################################################################################";
        Frequence.setActionCommand(solu);
    }//GEN-LAST:event_FrequenceActionPerformed

    private void BRUTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRUTEActionPerformed
        clickBrute=true;
        clickFrequence=false;
        String solution ="";
        String con;
        for(int k=0;k<26;k++){
            solution=solution+"\n#####################################\t      pour k= "+k+"          ###############################\n\n\t\t\t\t\t";
            for(int i=0;i<TEXTE.getText().length();i++){
                int codNum=clas.codageNum(TEXTE.getText().charAt(i));
                int chif=clas.dechiffrementC(codNum,k);
                con=clas.decodeNummajuscule(chif)+"";
                solution=solution.concat(con);

            }
            solution=solution+" \n\n";
            BRUTE.setActionCommand(solution);
    }//GEN-LAST:event_BRUTEActionPerformed
    }
    private void PrecedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecedentActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_PrecedentActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CesarCryptanalyse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CesarCryptanalyse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CesarCryptanalyse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CesarCryptanalyse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CesarCryptanalyse().setVisible(true);
            }
        });
    }
    SubMonoAlph clas=new SubMonoAlph();
    ButtonGroup group = new ButtonGroup();
    int max=0;
		int max1=0;
		int indic=0;
		int indic1=0;
		int mx=0;
		int q[]={1,3,5,7,9,11,15,17,19,21,23,25};
                
                boolean clickBrute,clickFrequence;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane AFFICHER;
    private javax.swing.JRadioButton BRUTE;
    private javax.swing.JRadioButton Frequence;
    private javax.swing.JToggleButton Precedent;
    private javax.swing.JTextArea TEXTE;
    private javax.swing.JToggleButton VALIDER;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
